fix a bit.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -7,18 +7,24 @@ CACHE_DIR=$2
 LP_DIR=`cd $(dirname $0); cd ..; pwd`
 
 cd $BUILD_DIR
-file1="Makefile"
-file2="makefile"
-if [ -f $file1 ]
+autogen_file="autogen.sh"
+configure_file="configure.ac"
+if [ -f $autogen_file ]
 then
-    echo "-----> Makefile found"
-elif [ -f $file2 ]
-then
-    echo "-----> makefile found"
+    echo "-----> autogen found"
 else
-    echo "-----> No Makefile found.Compilation cannot continue."
+    echo "-----> No autogen found.Compilation cannot continue."
+    exit 1;
+fi
+if [ -f $configure_file ]
+then
+    echo "-----> configure found"
+else
+    echo "-----> No configure found.Compilation cannot continue."
     exit 1;
 fi
 
+./autogen.sh
+./configure
 make
 echo "-----> Compilation done"
